version: '3.9'

services:
  web:
    build: .
    command: python manage.py run --host='0.0.0.0' --port='5055'
    volumes:
      - ./:/usr/src/app/
    ports:
      - 5055:5055
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: flask_dbname
      POSTGRES_USER: flask_user
      POSTGRES_PASSWORD: flask_pw
#    ports:
#      - 5405:5432

volumes:
  postgres_data: